Unblock armhf s390x and ppc64el snap builds
      generating cffi module 'build/temp.linux-s390x-3.8/pygit2._libgit2.c'
      creating build/temp.linux-s390x-3.8
      building 'pygit2._pygit2' extension
      creating build/temp.linux-s390x-3.8/src
      s390x-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/include -I/build/gitless-snap/parts/gitless-cli/install/include -I/usr/include/python3.8 -c src/blob.c -o build/temp.linux-s390x-3.8/src/blob.o
      In file included from src/blob.c:30:
      src/diff.h:33:10: fatal error: git2.h: No such file or directory
         33 | #include <git2.h>
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/s390x-linux-gnu-gcc' failed with exit code 1
      [end of output]